sudo: false
language: node_js
install: true
script: ./test/travis.sh
env:
  matrix:
  - NODE=6
  - NODE=5
  - NODE=4
  - BROWSER=chrome
  - BROWSER=firefox
  - BROWSER=safari
  - BROWSER=android
  - BROWSER=iphone
  global:
  - secure: cpG4Ary76R0hjfL6SxZn3qrrxPILoYCKPMWhLX2L9ibEZz7He+i9svJucbbuOc0kXP64ipzFwe/jEMZbpCAv4iE2HAZ65AhoACvnva5wOeT78aKhxqxJxWcCbWlGQ5sWdWrQJmbs5rQ7PKNFgNwqW6xsj1cENOSBIu7R/shq+g/J6G7KAaN+4VsO3bY23tbGV8fISxNw18KVPrpXHY9YficQ/+86DwWnk1BMBnbt+Z+KGQ/JuzN9jlVmohEGe/6MLN35EZWwVvHuW1LFnl441m1aWNFmsd6XyaPRbrWtWQ++NWFCjV9Pq/bY2FNJS69xb8zGwrFznY/MS5rpSsF/eoG+bpESSGW57iiX5ZmWj9ymfmZxDdKiOq/NTxiQbXz6n/rc1QdsYrRSSwl2lHEaFhhK9Go2v778rwfohkX5DKDncLx+h9RceV1vVANwPIyYCBPA3b5hSu56lxo34z0ZM5PMPzV6torwjb0J4gsOQygPJjuIdoxsJb0QGLImXTzdmdDNoCpVb15aOiWaR6ckYSyB1VAEFPCZcOML2nSNcYWbDoOqlbNjP2BsRmDip+b7QOBPQU8oHmzMutCNg5H2uvArxBWDtQ6qDajDHE48hO2bvLvzpzXn4XyMzmI1byobBpkHjc4u1OcPEEH7D1TbOfLKs6Xeu1O/NN0IVD2OoSk=
  - secure: S6SLu08nSxVeFLT7vUlKceddGN9ihiHV3/yrzS1Vfdtj+Dx0p50k8B8oGkGfqZbDI+b5rbZ1hh/P2/cfz2+FYOGbNoJ1yhqX8x99M6XO/zbp2nm6LAUyShBJBXDYtu6t7VAMWaWIwQZqojdja2XQ8vIU6B6TpaAmtN93kq34TLypHcm5YgkdO6vaMJxlPfVuW66k1WeJ7iFOyJAKuk84AqbIOOCnaHQKj2m0Css/lSYoNZICyq5FYqgP30uf+6OFpGFMT8jOwbCpBoxFeCtvHIxF4FJ6ESHRAdNTzsvVJMzxT8+J1Cs7DXoPgC3DuZmI/36bHtRC63TZUnfxOZG6SXxXUyD10YGFM8uYKcmRau3996PFOKM9YWz1oFpmxXiE9sBCooT9jR9sLd7IsoxucCYcbpZ7/D6nw4dBOLZb4uJDwpPm472L+yj5nldGoynJshLuFWrjZD1JLBff6MvOO9LKtvHQS7aPw2chMloczAcUjT0TENgvrvQo6z+eCz87K2bGP8qBfaXC88PeQiLLwn+5L7UfrYAD1mOYQrwS59oIgFELnEAcD+70cPl1uYulPgobd3fdHvq2G/jsrAGAn738GvO3sYNCewFlI4sSCojSChtSOyLgZr5q9gy0Uldh6bfLrxR0pB81Yt2FqY8d5UgysP2AAICvS1A/g946nu8=
notifications:
  email: false
